# Generated by Django 6.0.2 on 2026-03-11 18:16

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_large',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=0.5, size=[1200, 1200], upload_to='avatars/large/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_medium',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=0.5, size=[800, 800], upload_to='avatars/medium/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_small',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=85, scale=0.5, size=[300, 300], upload_to='avatars/small/'),
        ),
    ]
