# Generated by Django 6.0.2 on 2026-03-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_image_large_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_large',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_medium',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_small',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
